countdown_rate = 400;
countdown = countdown_rate;
default_gun = sprite_index;
gun_sprite = default_gun;
default_bullet = obj_bullet;
gun_bullet = default_bullet;
gun_range = 200;
range = gun_range;
//if(!global.has_gun){ instance_destroy(); }